import { IBudgetDetails } from "src/app/core/models/budget-details";

export const budgetDetailsMock: IBudgetDetails = {
  data: {
    budget: {
      id: "7b201abf-8380-4148-afa8-8935de0509db",
      name: "second budget",
      last_modified_on: "2021-01-23T19:25:01+00:00",
      date_format: { format: "MM/DD/YYYY" },
      currency_format: {
        iso_code: "USD",
        example_format: "123,456.78",
        decimal_digits: 2,
        decimal_separator: ".",
        symbol_first: true,
        group_separator: ",",
        currency_symbol: "$",
        display_symbol: true,
      },
      first_month: "2021-01-01",
      last_month: "2021-02-01",
      accounts: [
        {
          id: "fbf45ffe-1b29-41f3-a6e5-f0b8d8a9d2ae",
          name: "test account",
          type: "cash",
          on_budget: true,
          closed: false,
          note: null,
          balance: 4320,
          cleared_balance: 4320,
          uncleared_balance: 0,
          transfer_payee_id: "e6f80dac-67fc-4b3b-a570-a8941eca9e30",
          deleted: false,
        },
      ],
      payees: [
        {
          id: "afc6d13c-19df-45dc-923e-8b58a4fa2ef6",
          name: "Starting Balance",
          transfer_account_id: null,
          deleted: false,
        },
      ],
      payee_locations: [],
      category_groups: [
        {
          id: "3ae4344e-c3b3-4623-8bd3-89f2a0b4b963",
          name: "Internal Master Category",
          hidden: false,
          deleted: false,
        },
      ],
      categories: [
        {
          id: "2fc6e4f2-8951-43ba-9602-58c492fb5be6",
          category_group_id: "3ae4344e-c3b3-4623-8bd3-89f2a0b4b963",
          name: "To be Budgeted",
          hidden: false,
          original_category_group_id: null,
          note: null,
          budgeted: 0,
          activity: 4320,
          balance: 4320,
          goal_type: null,
          goal_creation_month: null,
          goal_target: 0,
          goal_target_month: null,
          goal_percentage_complete: null,
          deleted: false,
        },
      ],
      months: [
        {
          month: "2021-03-01",
          note: null,
          income: 0,
          budgeted: 0,
          activity: 0,
          to_be_budgeted: 3320,
          age_of_money: null,
          deleted: false,
          categories: [
            {
              id: "f4cb94ac-6953-4fc7-9167-85d838f69c7d",
              category_group_id: "3ae4344e-c3b3-4623-8bd3-89f2a0b4b963",
              name: "None",
              hidden: false,
              original_category_group_id: null,
              note: null,
              budgeted: 0,
              activity: 0,
              balance: 0,
              goal_type: null,
              goal_creation_month: null,
              goal_target: 0,
              goal_target_month: null,
              goal_percentage_complete: null,
              deleted: false,
            },
          ],
        },
      ],
      transactions: [
        {
          id: "e7d04908-6123-456c-b8dd-187c71e495e5",
          date: "2021-01-25",
          amount: 4324,
          memo: null,
          cleared: "cleared",
          approved: true,
          flag_color: null,
          account_id: "fbf45ffe-1b29-41f3-a6e5-f0b8d8a9d2ae",
          payee_id: "afc6d13c-19df-45dc-923e-8b58a4fa2ef6",
          category_id: "2fc6e4f2-8951-43ba-9602-58c492fb5be6",
          transfer_account_id: null,
          transfer_transaction_id: null,
          matched_transaction_id: null,
          import_id: null,
          deleted: false,
        },
      ],
      subtransactions: [],
      scheduled_transactions: [],
      scheduled_subtransactions: [],
    },
    server_knowledge: 48,
  },
};
